#!/bin/bash

# apply all the kubernetes configs for the hello app

kubectl apply -f ./k8s/hello/namespace.yaml
kubectl apply -f ./k8s/hello/deployment.yaml
kubectl apply -f ./k8s/hello/service.yaml
kubectl apply -f ./k8s/hello/headless-service.yaml
