#!/bin/bash

# delete all pods
kubectl delete --all pods --namespace=monitoring

# deete all deployments
kubectl delete --all deployments --namespace=monitoring

# delete all services
kubectl delete --all services --namespace=monitoring
