#!/bin/bash

# delete all pods
kubectl delete --all pods --namespace=hello

# deete all deployments
kubectl delete --all deployments --namespace=hello

# delete all services
kubectl delete --all services --namespace=hello
