apiVersion: v1
kind: Service
metadata:
  name: service
  namespace: hello
spec:
  ports:
    - port: 6000
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: hello
  type: LoadBalancer
